# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= adpcm.o AudioCodec.o g72x.o g726.o g726_16.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}


include $(MAKEPARAM)




